import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";

const noto_sans = Noto_Sans({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Test Task for DoctorWorld",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={noto_sans.className}>
        <header>
          <img src="/Vector 45.png" alt=" " />
          <img src="/Vector 46.png" alt=" " />
          <img src="/Vector 47.png" alt=" " />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
